Resources:
  MatchesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: matchId
          AttributeType: S
        - AttributeName: hostUserId
          AttributeType: S
      KeySchema:
        - AttributeName: matchId
          KeyType: HASH
        - AttributeName: hostUserId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
